name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LUA_PATH: ./src/?.lua

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install libreadline5
    - name: Run tests
      run: ./bin/Linux/lua-5.3.4/lua ./src/test_runner.lua -d ./tests -et efail
