name: Build

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      LUA_PATH: ./src/?.lua

    steps:
    - uses: actions/checkout@v1
    - name: Run tests on Linux
      if: matrix.os == 'ubuntu-latest'
      run: ./bin/Linux/lua-5.3.5/lua ./src/utest_runner.lua -d ./tests -et efail
      shell: bash
    - name: Run tests on Windows
      if: matrix.os == 'windows-latest'
      run: .\bin\Windows\lua-5.4.0\lua.exe .\src\utest_runner.lua -d .\tests -et efail
      shell: cmd
