name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LUA_PATH: ./src/?.lua

    steps:
    - uses: actions/checkout@v1
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.3"
    - name: Run tests
      run: lua ./src/test_runner.lua -d ./tests -et efail
