name: spec

on: [push]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        luaVersion: ["5.3", "luajit-2.0.5"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: ${{matrix.luaVersion}}
        
    - name: Navigate to src
      run: cd src
      
    - name: Run tests
      run: lua test_runner.lua -d ..\tests
